# Generated by Django 4.2.3 on 2023-08-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="profile_img",
            field=models.ImageField(
                blank=True,
                default="profileimages/person.png",
                null=True,
                upload_to="profileimages/",
            ),
        ),
    ]
