# Generated by Django 4.2.3 on 2023-08-11 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("like", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="postlike",
            old_name="to_photo",
            new_name="to_post",
        ),
    ]
