# Generated by Django 4.2.3 on 2023-08-01 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("group", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="groupmembersmodel",
            options={
                "verbose_name": "Group Member",
                "verbose_name_plural": "Group Members",
            },
        ),
        migrations.AlterModelOptions(
            name="groupmodel",
            options={
                "ordering": ["name"],
                "verbose_name": "Group",
                "verbose_name_plural": "Groups",
            },
        ),
        migrations.AlterField(
            model_name="groupmembersmodel",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="membership",
                to="group.groupmodel",
            ),
        ),
        migrations.AlterField(
            model_name="groupmembersmodel",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="group_member",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="groupmodel",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="groupmodel",
            name="members",
            field=models.ManyToManyField(
                through="group.GroupMembersModel",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Members",
            ),
        ),
        migrations.AlterField(
            model_name="groupmodel",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Name"),
        ),
    ]
